const createRandomRooms = () => {
  const roomTypes = ["deluxe", "classic", "standard"];
  const roomPrices = { deluxe: 100, classic: 80, standard: 50 };
  const rooms = [];

  for (let i = 1; i <= 100; i++) {
    const randomType = roomTypes[Math.floor(Math.random() * roomTypes.length)];
    rooms.push({
      roomNumber: i,
      roomType: randomType,
      pricePerHour: roomPrices[randomType],
    });
  }

  return rooms;
};

// Generate the array of rooms
const roomsArray = createRandomRooms();
console.log(roomsArray);

const RoomType = [
  { roomNumber: 1, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 2, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 3, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 4, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 5, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 6, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 7, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 8, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 9, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 10, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 11, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 12, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 13, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 14, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 15, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 16, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 17, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 18, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 19, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 20, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 21, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 22, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 23, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 24, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 25, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 26, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 27, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 28, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 29, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 30, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 31, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 32, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 33, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 34, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 35, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 36, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 37, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 38, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 39, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 40, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 41, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 42, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 43, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 44, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 45, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 46, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 47, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 48, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 49, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 50, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 51, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 52, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 53, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 54, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 55, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 56, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 57, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 58, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 59, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 60, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 61, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 62, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 63, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 64, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 65, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 66, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 67, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 68, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 69, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 70, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 71, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 72, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 73, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 74, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 75, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 76, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 77, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 78, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 79, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 80, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 81, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 82, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 83, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 84, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 85, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 86, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 87, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 88, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 89, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 90, roomType: "deluxe", pricePerHour: 100 },
  { roomNumber: 91, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 92, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 93, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 94, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 95, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 96, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 97, roomType: "classic", pricePerHour: 80 },
  { roomNumber: 98, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 99, roomType: "standard", pricePerHour: 50 },
  { roomNumber: 100, roomType: "standard", pricePerHour: 50 },
];

export default RoomType;
